### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by am2605**
This will build successfully using `mvn clean install`.  

Setup in eclipse requires a bit of faffing around (in particular adding cfparser and cflint as udpate sites).

@denuno are you able to show me how we build this and deploy it to /update-dev, and we can look at getting a new release out?

If you can show me the deploy process that would allow me to be a bit more self sufficient from here on.

### CODE REVIEW

**Comment by am2605** [comment]
I’ve put this on cfeclipse.org/update-nightly if anyone wants to try it.  Nothing groundbreaking here, just trying to get a useable build out again.

**Comment by bardware** [comment]
I started to look at this new release. I took a brand new eclipse 4.13 RC2 and installed CFeclipse from the [update-nightly site](https://cfeclipse.org/update-nightly/)

The [error](https://github.com/cfeclipse/cfeclipse/issues/117) that was permanently thrown, after a file was closed, seems gone. That's very good.
In the `Console` view I see some logs `AssistUtil#getFunctions: Resource not found`. I haven't found out by now that triggers these.

**Comment by am2605** [comment]
Thanks for testing @bardware.  I think I will push ahead with plans to release this and investigate the messages you see in the logs as a separate issue.  

I am not sure of the release process Denny was using, so I am going to investigate using something like travis-ci over the coming week with a view to cutting a stable release.

I also need to look at what to do about the various update sites.  It think traditionally /update-preview was "milestone" and /update was "stable".  I created "/update-nightly" some time ago because I needed somewhere to put my experimental builds that didn't go through the release process (since I didn't have any information about it.

How do folks feel about consolidating these into 2 only:

/update <- stable (ie. built from master branch)
/update-nightly <- bleeding edge (built from develop branch - in theory should be fairly stable anyway)

I'll make /update-dev and /update-preview aliases for /update-nightly so anyone that's using these continues to get bleeding edge builds

**Comment by am2605** [comment]
> In the `Console` view I see some logs `AssistUtil#getFunctions: Resource not found`. I haven't found out by now that triggers these.

Logged as #126

**Comment by am2605** [comment]
I'm going to close this as I'm still doing a bit of a tidy up.  I'm close to having this ready though.

**Pull request closed without merging**
